spring:
  application:
    name: gateway-server
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev


server:
  port: 53010

logging:
  level:
    root: info
    org:
      springframework: info
zuul:
  retryable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:53000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipaddress}:${spring.application.instance_id:${server.port}}

management:
  endpoint:
    web:
      exposure:
        include: refresh,health,info,env

feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types:
        - text/xml
        - application/xml
        - application/json
      min-request-size: 2048
    response:
      enabled: true







    #feign.hystrix.enabled = true
    #feign.compression.request.enabled = true
  #feign.compression.request.mime‐types[0] = text/xml
  #feign.compression.request.mime‐types[1] = application/xml
  #feign.compression.request.mime‐types[2] = application/json
  #feign.compression.request.min‐request‐size = 2048
  ignored-services: *
  add-host-header: true
  sensitive-headers: *
  routes:
    uaa-service:
      stripPrefix: false
      path: /uaa/**
    order-service:
      stripPrefix: false
      path: /order/**


