spring:
  application:
    name: uaa-service
  main:
    allow-bean-definition-overriding: true   #定义为true时，后定义的bean会覆盖掉之前的bean
  http:
    encoding:
      enabled: true
      charset: utf-8
  freemarker:
    enabled: true
    suffix: html
    request-context-attribute: rc     #引用地址，后面可以使用
    content-type: text/html
    charset: UTF-8
#mvc
  mvc:
    throw-exception-if-no-handler-found: true   #出现异常，抛出NoHandlerFoundException
  resources:
    add-mappings: false
#datasourse
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/user_db?useUnicode=true
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
        idle-timeout: 30000
        minimum-idle: 5
        maximum-pool-size: 10
        auto-commit: true
        max-lifetime: 18000000
        connection-timeout: 30000
        pool-name: DatebookHikariCP
    #      connection-test-query: SELECT

server:
  port: 53020
  tomcat:
    remote-ip-header: x-forwarded-for      #设定remote IP的header，如果remoteIpHeader有值，则设置为RemoteIpValve
    protocol-header:  x-forwarded-proto    #设定Header包含的协议，通常是 X-Forwarded-Proto，如果remoteIpHeader有值，则将设置为RemoteIpValve.s
  use-forward-headers: true
  servlet:
    context-path: /uaa

logging:
  level:
    root: info
    org:
      springframework:
        web: info
eureka:
  client:
    service-url:
      defaultZone: http://localhost:53000/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipaddress}:${spring.application.instance_id:${server.port}}
feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types:
        - text/xml
        - application/xml
        - application/json
      min-request-size: 2048
    response:
      enabled: true

